# Generated by Django 3.1 on 2020-08-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Type',
            field=models.CharField(choices=[('Full Time', 'full time'), ('Part Time', 'part time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
