# Generated by Django 3.1 on 2020-08-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
